# Generated by Django 2.1.7 on 2019-03-20 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diningroom',
            name='schedule',
            field=models.OneToOneField(help_text='Расписание уникально для каждого заведения (необходимо создать новое).', on_delete=django.db.models.deletion.CASCADE, to='eatery.Shedule', verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(help_text='При отсутствии категорий в меню необходимо добавить категорию с пустыми значениями.', on_delete=django.db.models.deletion.CASCADE, to='eatery.DishCategory', verbose_name='Категория'),
        ),
    ]
